### ISSUE TITLE
" $digest already in progress "  Error comes when request callback is called 

### ISSUE THREAD

**Issue by deepsaurabh** [jonsamwell/angular-http-batcher#11]
### Digest error is coming from angularJs file , when callback is called .
```javascript
 this.request.callback(result.statusCode, result.data, result.headerString, result.statusText); 
```

**Comment by jonsamwell** [comment]
Does this happen all the time or in specific scenarios?

**Comment by jonsamwell** [comment]
What is the code in the callback?

**Comment by deepsaurabh** [comment]
It is happening as 2 of the calls in batch of 4 are failing.
The code in the call back is from angular.min.js file - 
```javascript
function e(a, b, c) {
                       m && (200 <= a && a < 300 ? m.put(q, 
                       [a, b, Ob(c)]) : m.remove(q));
                       f(b, a, c);
                       i.$apply()
                   }
```
as soon as i.$apply() is called digest error is coming

**Comment by jonsamwell** [comment]
That will call your call back - could you try it without any code in your then function?  I can't seem to replicate it which indicates it is something in your code

**Comment by jonsamwell** [comment]
Closing as no replies to my questions.  Please re-open if you still need help

**Comment by deepsaurabh** [comment]
It was resolved by updating the version of angular. thanks
