### ISSUE TITLE
Client Cache Support?

### ISSUE THREAD

**Issue by sarg3nt** [jonsamwell/angular-http-batcher#15]
I noticed that the auto batcher does not seem to support client cached calls.  Is there a plan to implement this in the future?
I was just noodling it over and am not sure what the best method would be.
I don't know how you would tell that a previous request has cache headers set.  I've Googled it very quickly and haven't found much. 
Any thoughts?

Totally a low priority.  I'm currently working on a sprint item for our new website to investigate the caching of ajax requests and noticed they don't work with auto batcher.  I'd rather use auto batcher then have them cached so not a super huge deal but would like to have accurate information to get back to the team to.  So, let me know what your thoughts are.

**Comment by jonsamwell** [comment]
Yes this is interesting.  Let me have a play. It would be good that if you
set cache to true in your $http request the batcher would not send this
request if it has already been cached.
