### ISSUE TITLE
Usage with NodeJS

### ISSUE THREAD

**Issue by tamlyn** [jonsamwell/angular-http-batcher#19]
There are many batch request handlers for NodeJS (e.g. [multifetch](https://www.npmjs.com/package/multifetch), [batch-endpoint](https://www.npmjs.com/package/batch-endpoint), [express-batch](https://www.npmjs.com/package/express-batch)) but they batch requests by specifying them in the query string and combining the JSON responses in the body. I can't seem to find any that support `multipart/mixed` responses. Would you consider adding support for this alternate batching format? Or perhaps provide callbacks to allow customising the batching and unwrapping strategy?

**Comment by jonsamwell** [comment]
Hi @tamlyn,

Yeah I'd definitely want to add support for this.  Could you provide any example or better yet a node project (like the .net one) that has a batch endpoint that we help me develop and test against?

Thanks,

Jon

**Comment by jonsamwell** [comment]
@tamlyn any progress on this?

**Comment by jonsamwell** [comment]
Hopefully this is working now in the v1.11.0 release!

You will need to update your config object slightly to use the multifetch batch adapter and it should work after that.

```javascript
app.config([
            'httpBatchConfigProvider',
            function (httpBatchConfigProvider) {
                httpBatchConfigProvider.setAllowedBatchEndpoint(
                        'http://localhost:8080',
                        'http://localhost:8080/batch', {
                            batchRequestCollectionDelay: 500,
                            minimumBatchSize: 1,
                            ignoredVerbs: ['head', 'post', 'put', 'delete', 'patch'],
                            adapter: 'nodeJsMultiFetchAdapter'
                        });
            }
    ]);
```

see the test page 

https://github.com/jonsamwell/angular-http-batcher/blob/master/tests/node-multi-fetch.html

see the adapter here

https://github.com/jonsamwell/angular-http-batcher/blob/master/src/services/adapters/nodeJsMultiFetchAdapter.js

Let me know if it works and suits your needs!

**Comment by tamlyn** [comment]
Coooool!
