### ISSUE TITLE
setAllowedBatchEndpoint ignores enabled

### ISSUE THREAD

**Issue by benripley** [jonsamwell/angular-http-batcher#21]
When sending enabled: false to setAllowedBatchEndpoint, the requests are still being sent via a batched request.

    var batchOptions = {
      ignoredVerbs: ['head', 'put', 'post', 'delete'],
      enabled: false
    };
    batchConfigProvider.setAllowedBatchEndpoint('/api', '/batch', batchOptions);

    // batch requests are enabled...

**Comment by jonsamwell** [comment]
This is odd I have a few tests that cover this functionality?  I'll look into it.

**Comment by jonsamwell** [comment]
Sorry - I'll get around to this tonight.

**Comment by benripley** [comment]
Don't hurry on my account. It's quite easy to work around. I just thought
you'd want to know.

Thanks,
Ben

**Comment by jonsamwell** [comment]
Hi @benripley,

What version of the library are you using as I can't reproduce this?

Thanks,

Jon

**Comment by benripley** [comment]
Sorry. Looks like I had an old version. 1.2.0. I'll try this on the latest and let you know.

**Comment by benripley** [comment]
Sorry about that Jon. Wasn't aware that I had an old version. Closed.

**Comment by jonsamwell** [comment]
No worries!
