### ISSUE TITLE
NPM module

### ISSUE THREAD

**Issue by benmj** [jonsamwell/angular-http-batcher#23]
Hi,

This is a very useful module. Do you have any plans to release it as an npm module? My team and I build our code using CommonJS syntax, and currently have to shim this into our project.

Thanks!

**Comment by jonsamwell** [comment]
Sure! I'm just off out for a surf but I'll do it when I get back in a
couple of hours!  Glad you're finding it useful!

**Comment by benmj** [comment]
Well, thanks!

And watch out for sharks.

-ben jacobs

**Comment by jonsamwell** [comment]
@benmj I hate sharks.  There's been loads of sightings around Sydney the last couple of weeks :-(

On a lighter note I've published this on NPM https://www.npmjs.com/package/angular-http-batcher

Let me know if you have any ideas for improving the module.
