### ISSUE TITLE
Several differents rootUrls for same app??

### ISSUE THREAD

**Issue by fabm22** [jonsamwell/angular-http-batcher#30]
Hi, 

Sorry if my question si too noobish but I'd like to know if it is possible to specify, for the same app, several different endpoints, and if yes, how do I tell which one I'd like to use, as it seems the config through the "httpBatchConfigProvider" is whole app wide.

Should I specify it by angular.js modules or something ?

Thanks a lot for help!!

**Comment by fabm22** [comment]
Im a bit stupid, just by looking at the code with "mergedConfiguration" etc. I see you can set several endpoints, sorry  !

**Comment by jonsamwell** [comment]
Glad you sorted it out!
